Repository yfzm/poker-bot, pull requests merged in 2019-11, with the labels that each got.

#44 Lzy/refactor
  libs/card.py
  libs/game.py
  libs/table.py
  run.py
Labels: refactor

#52 Lzy/refactor
  libs/card.py
  libs/game.py
  libs/poker_cmp.py
  poker_test.py
  test/libs/test_poker_cmp.py
Labels: enhancement, refactor

#57 fix: poker-cmp-unittest
  test/libs/test_poker_cmp.py
Labels: bug

#59 fix bug: return non-zero when the tests fails
  poker_test.py
Labels: bug

#58 Feature/continue game
  .github/workflows/pythonapp.yml
  bots/game.py
  libs/manager.py
  libs/poker_bot.py
  libs/table.py
  slackapi/payload.py
Labels: bug, enhancement

#70 Feature/join and leave
  libs/game.py
  libs/player.py
  libs/table.py
  test/libs/test_game.py
Labels: enhancement

#75 auto login
  .gitignore
  bots/game.py
  libs/manager.py
  libs/player.py
  libs/storage.py
  libs/table.py
  local_checker.bat
  local_checker.sh
  test/libs/test_game.py
Labels: enhancement

#76 delete old message
  bots/game.py
  libs/table.py
  slackapi/client.py
Labels: enhancement

#77 Feature/show hand
  libs/game.py
  libs/table.py
Labels: enhancement
